# Generated by Django 4.1.3 on 2022-11-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='MY BLOG ', max_length=255),
        ),
    ]
